# -*- coding: utf-8 -*-
"""22 条主表数据（原文献、引用位置、替换候选、核实判定、可替代性裁定）。

题录字段一律取自本轮证据文件（证据/<编号>.txt）与《04-开题报告.md》原文。
"""
from __future__ import annotations

D = "证据/"
W = "阶段02-文献调研与开题/_知网核验/证据/"

ITEMS: list[dict] = [
    {
        "code": "RAG-1",
        "orig": "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks（P. Lewis 等，NeurIPS 2020）",
        "pos": "《04》2.1（L26）；3.2（L70，2 处）；参考文献[1]",
        "purpose": "交代 RAG 框架源头：参数化记忆＋非参数化记忆、\"切分→向量化→索引→相似度检索→条件生成\"基本流程；是本课题 Baseline 2（普通 Vector RAG）与消融 A 组的技术源头",
        "lang": "英文",
        "cand_title": "检索增强生成综述：方法与应用",
        "cand_authors": "王鑫林、李岩、马超凡、李硕",
        "cand_source": "《计算机科学》2026 年第 07 期",
        "cand_volpage": "卷号与页码页面未提供（仅年到 2026、期到 07）",
        "cnki_id": "CJFDTOTAL-JSJA202607012",
        "cand_url": "https://www.cnki.com.cn/Article/CJFDTotal-JSJA202607012.htm",
        "verdict": "核实通过（题录一致）",
        "verdict_note": "题名、四位作者、《计算机科学》2026 年 07 期与表中一致",
        "evidence": D + "RAG-1.html / RAG-1.txt",
        "fulltext": "②需登录下载（页面提供\"下载全文\"入口，指向 wap.cnki.net；未点击）",
        "found": "奠基性：RAG 原始论文（Lewis 2020）无中文等价替代。中文综述可支撑\"方法体系与国内进展\"，但不能替代\"RAG 框架由 Lewis 等提出\"这一史实性论断；建议原英文文献保留为国际前沿引用",
        "recommend": "可采纳为中文综述引用（改写口径为\"国内 RAG 方法体系梳理\"），同时保留 Lewis 2020 作为国际前沿",
        "alt": "池内 RAG-15（刘澳迪等《软件学报》综述）、RAG-20、RAG-21、RAG-22 同为 RAG 中文综述，其中 RAG-15 刊于《软件学报》（CCF A 中文期刊），权威性高于本候选，建议作者优先考虑",
    },
    {
        "code": "KG-21",
        "orig": "面向应急管理的金融突发事件事理知识图谱构建与分析研究（刘政昊等，信息资源管理学报 2022, 12(3): 137-151）",
        "pos": "《04》2.1（L26）；3.1（L42，2 处）；3.5（L124）；参考文献[2]",
        "purpose": "国内最直接的事件中心化金融 KG 对标工作：事件本体设计、事件抽取与事件泛化、双层结构（事件与知识实体约 19.97 万个、关系约 44.50 万条）、包商银行案例的演化逻辑",
        "lang": "中文",
        "cand_title": "保留不动（已是中文，上轮知网核验已通过）",
        "cand_authors": "刘政昊、曾曦、张志剑",
        "cand_source": "《信息资源管理学报》2022 年第 03 期",
        "cand_volpage": "2022, 12(3): 137-151（《03》题录口径）",
        "cnki_id": "CJFDTOTAL-XNZY202203011",
        "cand_url": "https://www.cnki.com.cn/Article/CJFDTotal-XNZY202203011.htm",
        "verdict": "保留不动（本轮不替换；题录自上轮核验起一致）",
        "verdict_note": "本轮沿用上轮证据 证据/KG-21_1.html；页面题名、三位作者、刊期与《03》一致",
        "evidence": D + "KG-21_1.html / KG-21_1.txt（上轮抓取，本轮未重复请求）",
        "fulltext": "②需登录下载；全文已在手：文献PDF/KG-21_Liu2022_FinancialEmergencyKG.pdf",
        "found": "—",
        "recommend": "保留",
        "alt": "—",
    },
    {
        "code": "KG-5",
        "orig": "FinKario: Event-Enhanced Automated Construction of Financial Knowledge Graph（X. Li 等，ACL 2026: 9826-9845）",
        "pos": "《04》3.1（L46）；3.5（L124）；参考文献[3]",
        "purpose": "证明\"事件增强的金融 KG\"已具备从自动构建（研报/公告抽取事件型三元组、30 万+实体、19 类关系）到两阶段图检索的完整链路；用于关系粒度对照与\"与 GraphRAG 家族的区别\"",
        "lang": "英文",
        "cand_title": "基于注意力机制的知识图谱推理方法研究",
        "cand_authors": "刘晓鹏（导师：赵军，页面未提供导师字段）",
        "cand_source": "硕士学位论文，宁夏大学，2026",
        "cand_volpage": "学位论文无卷期页：学位授予单位 宁夏大学、学位级别 硕士、学位授予年份 2026",
        "cnki_id": "CDMD-10749-1026398565",
        "cand_url": "https://cdmd.cnki.com.cn/Article/CDMD-10749-1026398565.htm",
        "verdict": "核实通过（题录一致）",
        "verdict_note": "题名、作者、学位类型/单位/年份与表中一致；表中\"导师：赵军\"页面未提供，无法核实",
        "evidence": D + "KG-5.html / KG-5.txt",
        "fulltext": "②需登录下载（页面\"下载全文\"入口无直达 href；未点击）",
        "found": "无等价替代：FinKario 是\"事件增强金融 KG 自动构建＋两阶段图检索\"的最新同构工作，中文池内没有同口径工作",
        "recommend": "建议改选：本候选只覆盖\"KG 推理方法\"，撑不住表中\"两阶段图检索\"落点；池内 KG-7（刘政昊等，金融证券 KG 构建与相关股票发现，中文核心/CSSCI）更贴合\"A 股金融 KG 构建\"",
        "alt": "池内 KG-7《知识关联视角下金融证券知识图谱构建与相关股票发现》（数据分析与知识发现 2022, 6(2/3): 184-201）；KG-26《面向金融知识图谱的动态关系预测方法研究》（数据分析与知识发现 2023, 7(9): 39-50）",
    },
    {
        "code": "KG-9",
        "orig": "Doc2EDAG: An End-to-End Document-level Framework for Chinese Financial Event Extraction（S. Zheng 等，EMNLP-IJCNLP 2019: 337-346）",
        "pos": "《04》3.1（L50）；参考文献[4]",
        "purpose": "\"论元跨句分散\"与\"多事件共存\"的任务设定先例：以实体有向无环图（EDAG）直接生成事件表，说明文档级抽取与句级抽取的区别",
        "lang": "英文",
        "cand_title": "基于多维指令集微调的大语言模型金融事件抽取",
        "cand_authors": "杨维、才智杰",
        "cand_source": "《计算机科学与探索》2026 年第 08 期",
        "cand_volpage": "卷号与页码页面未提供（仅年到 2026、期到 08）",
        "cnki_id": "CJFDTOTAL-KXTS202608009",
        "cand_url": "https://www.cnki.com.cn/Article/CJFDTotal-KXTS202608009.htm",
        "verdict": "核实通过（题录一致）",
        "verdict_note": "题名、两位作者、刊期与表中一致",
        "evidence": D + "KG-9.html / KG-9.txt（沿用上轮 _1 证据并重抽字段）",
        "fulltext": "②需登录下载（页面\"下载全文\"入口，指向 wap.cnki.net；未点击）",
        "found": "奠基性：Doc2EDAG 是中文金融文档级事件抽取的经典工作，中文无等价替代（候选只是同类任务的新方法）",
        "recommend": "可采纳为\"国内大模型金融事件抽取\"引用（支撑事件结构化表示与实现路径参考），但需保留 Doc2EDAG 作为方法先例；正文中\"文档级/EDAG 事件表\"的表述必须继续引原英文文献",
        "alt": "池内无更贴近 Doc2EDAG 的文档级中文候选；KG-18（CasEE，重叠事件抽取）可作为\"一句多事件\"标注规则的补充",
    },
    {
        "code": "KG-16",
        "orig": "DocEE: A Large-Scale and Fine-grained Benchmark for Document-level Event Extraction（M. Tong 等，NAACL-HLT 2022: 3970-3982）",
        "pos": "《04》3.1（L52）；参考文献[5]",
        "purpose": "文档级抽取的评测现状与难度：2.7 万+事件、18 万+论元、当时最优 F1 仅 41%（人工 85%），支撑 200 条评测集的三层标注字段设计与\"人工金标准必要性\"",
        "lang": "英文",
        "cand_title": "基于跨度和网络结构的篇章级事件抽取研究",
        "cand_authors": "牛冰宇（导师：廖涛，页面未提供导师字段）",
        "cand_source": "硕士学位论文，安徽理工大学，2026（表中未写学校，页面补足）",
        "cand_volpage": "学位论文无卷期页：学位授予单位 安徽理工大学、学位级别 硕士、学位授予年份 2026",
        "cnki_id": "CDMD-10361-1026321974",
        "cand_url": "https://cdmd.cnki.com.cn/Article/CDMD-10361-1026321974.htm",
        "verdict": "核实通过（题录一致）",
        "verdict_note": "题名、作者、学位类型与年份一致；表中未写学位授予单位，页面为\"安徽理工大学\"（属补充信息）；表中\"导师：廖涛\"页面未提供，无法核实",
        "evidence": D + "KG-16.html / KG-16.txt",
        "fulltext": "②需登录下载（页面\"下载全文\"入口无直达 href；未点击）",
        "found": "奠基性（基准类）：DocEE 的规模、细粒度论元类型与 F1/人工对比数据无中文等价替代；候选只能支撑\"篇章级抽取方法与跨度识别\"",
        "recommend": "可采纳但须改写论证口径：把\"最优 F1 41% vs 人工 85%\"的数据句保留给 DocEE 原文，候选只用于\"国内篇章级抽取方法\"；或改选池内无更优项后采纳",
        "alt": "池内 KG-20（事理图谱研究综述）与 KG-24（LLM 增强的 KGQA 综述）分别偏事理图谱与问答，不替代本落点",
    },
    {
        "code": "KG-17",
        "orig": "DocEE-zh: A Fine-grained Benchmark for Chinese Document-level Event Extraction（M. Liu 等，Findings of EMNLP 2024: 637-649）",
        "pos": "《04》3.1（L54）；参考文献[6]",
        "purpose": "中文标注规范与难度预判：3.6 万+事件、21 万+论元、最优 F1 45.88；支撑 200 条评测集的中文标注口径与本体 schema 中文适配",
        "lang": "英文",
        "cand_title": "基于自适应GNN的篇章级金融事件抽取系统研究与实现",
        "cand_authors": "廖慧之（导师：臧洁，页面未提供导师字段）",
        "cand_source": "硕士学位论文，辽宁大学，2025",
        "cand_volpage": "学位论文无卷期页：学位授予单位 辽宁大学、学位级别 硕士、学位授予年份 2025",
        "cnki_id": "CDMD-10140-1026248350",
        "cand_url": "https://cdmd.cnki.com.cn/Article/CDMD-10140-1026248350.htm",
        "verdict": "核实通过（题录一致）",
        "verdict_note": "题名、作者、学位类型/单位/年份与表中一致；表中\"导师：臧洁\"页面未提供，无法核实",
        "evidence": D + "KG-17.html / KG-17.txt（沿用上轮 _1 证据并重抽字段）",
        "fulltext": "②需登录下载（页面\"下载全文\"入口无直达 href；未点击）",
        "found": "奠基性（基准类）：DocEE-zh 的规模与 F1 45.88 数据无中文等价替代；候选可支撑\"中文金融篇章级抽取的系统实现与论元分散难点\"",
        "recommend": "可采纳但须改写论证口径：中文标注规范与规模数据仍引 DocEE-zh；候选用于\"金融场景系统实现\"",
        "alt": "池内无更贴近的中文基准类候选",
    },
    {
        "code": "KG-19",
        "orig": "MAVEN-ERE: A Unified Large-scale Dataset for Event Coreference, Temporal, Causal, and Subevent Relation Extraction（X. Wang 等，EMNLP 2022: 926-941）",
        "pos": "《04》3.1（L58）；3.5（L124）；参考文献[7]",
        "purpose": "事件—事件关系（共指、时序、因果、子事件）的统一标注框架与规模数据；事件共指链是同源事件合并（去重）的直接依据",
        "lang": "英文",
        "cand_title": "外部知识增强的事件共指消解方法",
        "cand_authors": "徐昇、李培峰、朱巧明",
        "cand_source": "《软件学报》2025 年第 11 期",
        "cand_volpage": "卷号与页码页面未提供（仅年到 2025、期到 11）",
        "cnki_id": "CJFDTOTAL-RJXB202511014",
        "cand_url": "https://www.cnki.com.cn/Article/CJFDTotal-RJXB202511014.htm",
        "verdict": "核实通过（题录一致）",
        "verdict_note": "题名、三位作者、刊期与表中一致（表中未写年份/期号，页面为 2025 年 11 期）",
        "evidence": D + "KG-19.html / KG-19.txt（沿用上轮 _1 证据并重抽字段）",
        "fulltext": "②需登录下载（页面\"下载全文\"入口，指向 wap.cnki.net；未点击）",
        "found": "奠基性（资源类）：四类事件关系统一标注与规模化数据（共指链 103,193 条等）无中文等价替代；候选仅对应\"事件共指消解\"一点",
        "recommend": "可采纳为\"事件共指消解\"的中文方法引用（《软件学报》权威性高），但四类关系建模与去重口径仍须引 MAVEN-ERE；另可补池内 KG-20（事理图谱综述）",
        "alt": "池内 KG-20《事理图谱研究综述》（计算机工程与应用 2026, 62(13): 68-86）可作事件关系建模的综述补充",
    },
    {
        "code": "KG-28",
        "orig": "实体消歧综述（段宗涛、李菲、陈柘，控制与决策 2021, 36(5): 1025-1039）",
        "pos": "《04》3.1（L62）；3.5（L130、L132）；5.2（L218）；参考文献[8]",
        "purpose": "实体消歧任务定义与子任务划分（聚类/链接、候选生成/候选链接、局部/协同链接、NIL 问题）；\"中文缺少公开标准数据集与高质量中文目标知识库\"的立论依据；stock_code 锚定自定规则的文献依据",
        "lang": "中文",
        "cand_title": "保留不动（已是中文，上轮知网核验已通过）",
        "cand_authors": "段宗涛、李菲、陈柘",
        "cand_source": "《控制与决策》2021 年第 05 期",
        "cand_volpage": "2021, 36(5): 1025-1039（《03》题录口径）",
        "cnki_id": "CJFDTOTAL-KZYC202105001",
        "cand_url": "https://www.cnki.com.cn/Article/CJFDTotal-KZYC202105001.htm",
        "verdict": "保留不动（本轮不替换；题录自上轮核验起一致）",
        "verdict_note": "沿用《_知网核验》证据（KG-28.html / KG-28.txt）",
        "evidence": W + "KG-28.html / KG-28.txt（上轮核验，本轮未重复请求）",
        "fulltext": "②需登录下载；全文已在手：文献PDF/KG-28_Duan2021_EntityDisambiguationReview.pdf",
        "found": "—",
        "recommend": "保留",
        "alt": "—",
    },
    {
        "code": "KG-29",
        "orig": "JEL: Applying End-to-End Neural Entity Linking in JPMorgan Chase（W. Ding 等，AAAI 2021, 35(17): 15301-15308）",
        "pos": "《04》3.1（L64）；3.5（L130、L132）；5.2（L218）；参考文献[9]",
        "purpose": "金融领域公司名实体链接的工业实践对照：维基百科口径的通用链接器无法泛化到企业专有实体，只能自建正负样本并辅以人工校验",
        "lang": "英文",
        "cand_title": "面向开源情报的实体链接技术研究综述",
        "cand_authors": "韩雪、陈秋琼、戴耀、胡佳荣",
        "cand_source": "《情报工程》2025 年第 03 期",
        "cand_volpage": "卷号与页码页面未提供（仅年到 2025、期到 03）",
        "cnki_id": "CJFDTOTAL-QBGC202503007",
        "cand_url": "https://www.cnki.com.cn/Article/CJFDTotal-QBGC202503007.htm",
        "verdict": "核实通过（题录一致）",
        "verdict_note": "题名、四位作者、刊期与表中一致",
        "evidence": D + "KG-29.html / KG-29.txt",
        "fulltext": "②需登录下载（页面\"下载全文\"入口，指向 wap.cnki.net；未点击）",
        "found": "无等价替代：原论点是\"金融/企业专有实体的工业链接实践\"，中文综述只能支撑\"实体链接技术脉络与国内进展\"",
        "recommend": "不建议单独承担原论据：题录虽核实通过，但\"通用链接器不适配专有实体\"这一论据来自 JEL 的工业实践，本候选（开源情报综述）不含对应证据；若采纳，须改写论据并保留 JEL 原文",
        "alt": "池内无金融/企业实体链接的替代候选；《03》的 KG-28（实体消歧综述）可与 JEL 组成\"中文资源缺口＋工业实践困难\"的双证据",
    },
    {
        "code": "RAG-9",
        "orig": "From Local to Global: A Graph RAG Approach to Query-Focused Summarization（D. Edge 等，arXiv:2404.16130, 2024）",
        "pos": "《04》3.2（L72）；3.5（L126）；参考文献[10]",
        "purpose": "GraphRAG 全局摘要式路线：实体 KG＋社区检测＋社区摘要回答全局性问题；其输出是全局摘要而非可核查的具体事件证据，用于论证本课题与 GraphRAG 家族的区别",
        "lang": "英文",
        "cand_title": "融合双驱动检索与结构安全增强的GraphRAG多跳推理方法研究",
        "cand_authors": "陈岩（导师：顾树俊，页面未提供导师字段）",
        "cand_source": "硕士学位论文，齐鲁工业大学，2026",
        "cand_volpage": "学位论文无卷期页：学位授予单位 齐鲁工业大学、学位级别 硕士、学位授予年份 2026",
        "cnki_id": "CDMD-10431-1026344672",
        "cand_url": "https://cdmd.cnki.com.cn/Article/CDMD-10431-1026344672.htm",
        "verdict": "核实通过（题录一致）",
        "verdict_note": "题名、作者、学位类型/单位/年份与表中一致；表中\"导师：顾树俊\"页面未提供，无法核实；该页摘要栏为空，未公开摘要",
        "evidence": D + "RAG-9.html / RAG-9.txt",
        "fulltext": "②需登录下载（页面\"下载全文\"入口无直达 href；未点击）；页面摘要未公开",
        "found": "奠基性：GraphRAG（Edge 2024）是图 RAG 的开创性工作，\"社区摘要→全局摘要而非可核查证据\"的论断无中文等价替代",
        "recommend": "可采纳为\"国内 GraphRAG 多跳推理\"引用，但需保留 Edge 2024 作为 GraphRAG 家族源头与差异论证依据；池内 RAG-19（图检索增强生成研究综述）可作补充综述",
        "alt": "池内 RAG-19《图检索增强生成研究综述》（人工智能与机器人研究 2025, 14(2): 402-413）",
    },
    {
        "code": "RAG-10",
        "orig": "HippoRAG: Neurobiologically Inspired Long-Term Memory for Large Language Models（B. J. Gutierrez 等，NeurIPS 2024）",
        "pos": "《04》3.2（L74）；3.5（L126）；参考文献[11]",
        "purpose": "图遍历式路线：LLM＋KG＋个性化 PageRank，用一次图遍历近似完成多跳检索；作为 RQ3 路径深度/H2 与 0/1/2 跳图检索的方法参照",
        "lang": "英文",
        "cand_title": "基于图神经网络推理的知识图谱多跳问答方法研究",
        "cand_authors": "王东际（导师：卢玲，页面未提供导师字段）",
        "cand_source": "硕士学位论文，重庆理工大学，2026",
        "cand_volpage": "学位论文无卷期页：学位授予单位 重庆理工大学、学位级别 硕士、学位授予年份 2026",
        "cnki_id": "CDMD-11660-1026346236",
        "cand_url": "https://cdmd.cnki.com.cn/Article/CDMD-11660-1026346236.htm",
        "verdict": "核实通过（题录一致）",
        "verdict_note": "题名、作者、学位类型/单位/年份与表中一致；表中\"导师：卢玲\"页面未提供，无法核实",
        "evidence": D + "RAG-10.html / RAG-10.txt",
        "fulltext": "②需登录下载（页面\"下载全文\"入口无直达 href；未点击）",
        "found": "奠基性：HippoRAG 的海马体索引/PPR 一次遍历多跳检索机制无中文等价替代；候选可支撑\"KG 多跳问答的国内进展\"",
        "recommend": "可采纳为国内多跳问答进展引用（其\"推理路径评估粗放、噪声干扰\"等问题描述可支撑 H2 的必要性），但 PPR 式检索机制的表述须引 HippoRAG 原文",
        "alt": "池内 KG-24《大语言模型增强的知识图谱问答研究进展综述》（计算机科学与探索 2024, 18(11): 2887-2900）权威性更好，可作综述型替代",
    },
    {
        "code": "RAG-11",
        "orig": "Ragas: Automated Evaluation of Retrieval Augmented Generation（S. Es 等，arXiv:2309.15217, 2023）",
        "pos": "《04》3.2（L80）；参考文献[13]",
        "purpose": "无须参考答案的 RAG 评估指标体系：上下文精确率、上下文召回率、忠实度、答案相关性；检索指标（Recall@K、Precision@K、MRR、Complete Evidence Recall@K）与问答指标（Faithfulness 等）的定义来源",
        "lang": "英文",
        "cand_title": "基于文本图结构化的层次化检索增强生成方法",
        "cand_authors": "雋兆波",
        "cand_source": "《计算机工程与设计》2026 年第 08 期",
        "cand_volpage": "卷号与页码页面未提供（仅年到 2026、期到 08）",
        "cnki_id": "CJFDTOTAL-SJSJ202608032",
        "cand_url": "https://www.cnki.com.cn/Article/CJFDTotal-SJSJ202608032.htm",
        "verdict": "核实通过（题录一致）",
        "verdict_note": "题名、作者、刊期与表中一致",
        "evidence": D + "RAG-11.html / RAG-11.txt",
        "fulltext": "②需登录下载（页面\"下载全文\"入口，指向 wap.cnki.net；未点击）",
        "found": "奠基性：RAGAS 的无参考答案指标体系（Faithfulness 等）无中文等价替代；本候选是\"分块＋层次化检索\"的方法优化文，不含评估指标体系",
        "recommend": "不建议采纳（对原论点疑似不相关）：无法支撑\"检索指标/问答指标定义\"；建议保留 RAGAS 原文，评估类中文支撑改用 SYS-13 候选（RAG 效能评估）并明确其只是\"评估实践\"而非指标体系来源",
        "alt": "池内无 RAG 评估指标体系类中文文献；可考虑将本条目替换为 SYS-13 候选并调整两处落点分工",
    },
    {
        "code": "RAG-13",
        "orig": "HotpotQA: A Dataset for Diverse, Explainable Multi-hop Question Answering（Z. Yang 等，EMNLP 2018）",
        "pos": "《04》3.2（L80）；参考文献[14]",
        "purpose": "\"问题—答案—支撑事实\"的标注组织方式与证据召回口径；120 题多标签测试集的跳数标签与证据标注参照；Complete Evidence Recall@K 的口径来源",
        "lang": "英文",
        "cand_title": "基于检索增强的大语言模型问答方法研究",
        "cand_authors": "何伯磊（导师：凌震华，页面未提供导师字段）",
        "cand_source": "博士学位论文，中国科学技术大学，2026",
        "cand_volpage": "学位论文无卷期页：学位授予单位 中国科学技术大学、学位级别 博士、学位授予年份 2026",
        "cnki_id": "CDMD-10358-1026362151",
        "cand_url": "https://cdmd.cnki.com.cn/Article/CDMD-10358-1026362151.htm",
        "verdict": "核实通过（题录一致）",
        "verdict_note": "题名、作者、学位类型/单位/年份与表中一致；表中\"导师：凌震华\"页面未提供，无法核实",
        "evidence": D + "RAG-13.html / RAG-13.txt",
        "fulltext": "②需登录下载（页面\"下载全文\"入口无直达 href；未点击）",
        "found": "奠基性（资源类）：HotpotQA 的支撑事实标注范式与多跳数据构造无中文等价替代；候选是 RAG 问答方法论文，可支撑\"国内问答方法进展\"",
        "recommend": "可采纳为\"国内 RAG 问答方法\"引用（博士论文体量与证据标注实验可作为测试集设计参考），但\"支撑事实标注\"口径仍须引 HotpotQA 原文",
        "alt": "池内无多跳问答数据集中文候选（多为方法类）",
    },
    {
        "code": "RAG-24",
        "orig": "FActScore: Fine-grained Atomic Evaluation of Factual Precision in Long Form Text Generation（S. Min 等，EMNLP 2023: 12076-12100）",
        "pos": "《04》3.2（L82）；参考文献[15]",
        "purpose": "把长文本拆成原子事实逐条核验，以被知识源支持的原子事实比例度量事实精度；其\"细粒度、逐条可核验\"的评测粒度支撑本课题人工 0/1/2 忠实度评分的交叉校验",
        "lang": "英文",
        "cand_title": "AIGC嵌入图书馆知识发现服务的幻觉识别与信任度测量",
        "cand_authors": "禤德信",
        "cand_source": "《情报探索》2026 年第 09 期",
        "cand_volpage": "卷号与页码页面未提供（仅年到 2026、期到 09）",
        "cnki_id": "CJFDTOTAL-QBTS202609016",
        "cand_url": "https://www.cnki.com.cn/Article/CJFDTotal-QBTS202609016.htm",
        "verdict": "核实通过（题录一致）",
        "verdict_note": "题名、作者、刊期与表中一致",
        "evidence": D + "RAG-24.html / RAG-24.txt",
        "fulltext": "②需登录下载（页面\"下载全文\"入口，指向 wap.cnki.net；未点击）",
        "found": "奠基性：FActScore 的原子事实精度与自动评测器口径无中文等价替代；候选研究\"幻觉识别与信任度\"，与事实性评测相邻但不同口径",
        "recommend": "可采纳为\"国内幻觉识别与信任度\"引用（其事实性/溯源性/逻辑性三类幻觉可支撑指标设计讨论），但 Faithfulness 的原子事实口径仍须引 FActScore；池内 RAG-26（大语言模型幻觉研究综述）更贴题，建议二选一或互补",
        "alt": "池内 RAG-26《大语言模型幻觉研究综述》（人工智能与机器人研究 2026, 15(1): 156-167）",
    },
    {
        "code": "FIN-3",
        "orig": "FinanceBench: A New Benchmark for Financial Question Answering（P. Islam 等，arXiv, 2023）",
        "pos": "《04》3.3（L88、L102）；3.5（L128）；参考文献[16]",
        "purpose": "面向上市公司披露文件的金融问答基准：10,231 个问答对、40 家公司、361 份文件、证据链标注；支撑 120 题多标签测试集设计、证据链与参考答案、Complete Evidence Recall@K",
        "lang": "英文",
        "cand_title": "基于检索增强生成的金融智能问答方法研究",
        "cand_authors": "冯宇（导师：杜方，页面未提供导师字段）",
        "cand_source": "硕士学位论文，宁夏大学，2026",
        "cand_volpage": "学位论文无卷期页：学位授予单位 宁夏大学、学位级别 硕士、学位授予年份 2026",
        "cnki_id": "CDMD-10749-1026398545",
        "cand_url": "https://cdmd.cnki.com.cn/Article/CDMD-10749-1026398545.htm",
        "verdict": "核实通过（题录一致）",
        "verdict_note": "题名、作者、学位类型/单位/年份与表中一致；表中\"导师：杜方\"页面未提供，无法核实",
        "evidence": D + "FIN-3.html / FIN-3.txt",
        "fulltext": "②需登录下载（页面\"下载全文\"入口无直达 href；未点击）",
        "found": "奠基性（基准类）：FinanceBench 的规模、SEC 文件域与证据链标注无中文等价替代；候选只支撑\"国内金融 RAG 问答方法\"",
        "recommend": "可采纳为国内金融 RAG 问答进展引用，但基准规模与证据链口径须保留 FinanceBench；池内 FIN-24（金融决策支持知识获取综述）与 FIN-23（财务报告指标抽取智能体）可作补充",
        "alt": "池内 FIN-23《基于大语言模型的财务报告指标抽取智能体方法》（人工智能与机器人研究 2025, 14(6): 1361-1371）；FIN-24《面向金融决策支持的知识获取研究综述》（信息资源管理学报 2020, 10(3): 27-35）",
    },
    {
        "code": "FIN-16",
        "orig": "Question Answering Over Temporal Knowledge Graphs（A. Saxena 等，ACL-IJCNLP 2021: 6663-6676）",
        "pos": "《04》3.3（L92、L102）；3.5（L126）；参考文献[17]",
        "purpose": "时序知识图谱问答基准 CRONQUESTIONS 与时序图谱嵌入模型 CRONKGQA；边表示为带有效时间区间（起止时间）；\"仅靠静态图谱问答方法在时序问题上会大幅退化\"的立论依据",
        "lang": "英文",
        "cand_title": "基于多粒度隐含时态感知的时序知识图谱问答研究",
        "cand_authors": "方纪祥（导师：卢玲，页面未提供导师字段）",
        "cand_source": "硕士学位论文，重庆理工大学，2026",
        "cand_volpage": "学位论文无卷期页：学位授予单位 重庆理工大学、学位级别 硕士、学位授予年份 2026",
        "cnki_id": "CDMD-11660-1026346229",
        "cand_url": "https://cdmd.cnki.com.cn/Article/CDMD-11660-1026346229.htm",
        "verdict": "核实通过（题录一致）",
        "verdict_note": "题名、作者、学位类型/单位/年份与表中一致；表中\"导师：卢玲\"页面未提供，无法核实",
        "evidence": D + "FIN-16.html / FIN-16.txt",
        "fulltext": "②需登录下载（页面\"下载全文\"入口无直达 href；未点击）",
        "found": "奠基性（基准类）：\"340 倍规模\"\"静态方法大幅退化\"等结论来自 CRONKGQA 原文，无中文等价替代；候选可支撑\"国内时序 KGQA 与时态感知\"",
        "recommend": "可采纳为国内时序 KGQA 进展引用（支撑 H3 与时序子集构建的国内依据），但基准与退化结论仍须引 CronKGQA 原文",
        "alt": "池内无更贴近的时序 KGQA 中文候选",
    },
    {
        "code": "FIN-17",
        "orig": "TempoQR: Temporal Question Reasoning over Knowledge Graphs（C. Mavromatis 等，AAAI 2022, 36(5): 5825-5833）",
        "pos": "《04》3.3（L94、L102）；3.5（L126）；参考文献[18]",
        "purpose": "时间感知的问题分解与稀疏子图检索：把问句编码为实体/时间/上下文三类表示，检索稀疏子图并联合推理，显式处理隐含时间约束；支撑 H3 与消融 D 组（时间过滤）",
        "lang": "英文",
        "cand_title": "SARIMA嵌入的时序知识图谱推理",
        "cand_authors": "吴钰、胡友德、冯桐、杜滢明、曹晗、唐静、李新兵",
        "cand_source": "《电子技术应用》2026 年第 06 期",
        "cand_volpage": "卷号与页码页面未提供（仅年到 2026、期到 06）",
        "cnki_id": "CJFDTOTAL-DZJY202606022",
        "cand_url": "https://www.cnki.com.cn/Article/CJFDTotal-DZJY202606022.htm",
        "verdict": "核实通过（题录一致）",
        "verdict_note": "题名与表中一致；作者表中写\"吴钰、胡友德、冯桐等\"，页面为 7 位作者全列（属补充信息）",
        "evidence": D + "FIN-17.html / FIN-17.txt",
        "fulltext": "②需登录下载（页面\"下载全文\"入口，指向 wap.cnki.net；未点击）",
        "found": "奠基性：TempoQR 的\"问题分解＋时间约束下的稀疏子图检索\"无中文等价替代；候选是时序 KG 推理的周期建模（SARIMA＋嵌入），不做问答与时间过滤",
        "recommend": "可采纳但须改写论证口径为\"国内时序知识图谱推理与时间序列建模\"；H3 的问题分解/时间过滤论证仍须引 TempoQR 原文",
        "alt": "池内无时间约束问答类中文候选；FIN-16 候选（多粒度时态感知 KGQA）与 FIN-17 候选可形成\"问答＋推理\"两条国内进展",
    },
    {
        "code": "FIN-20",
        "orig": "FinReflectKG -- HalluBench: GraphRAG Hallucination Benchmark for Financial Question Answering Systems（M. Kumar 等，arXiv:2603.20252, 2026）",
        "pos": "《04》3.3（L98）；3.5（L126、L128）；参考文献[19]",
        "purpose": "金融 RAG 幻觉基准：SEC 10-K 上 755 条标注样本（覆盖 300 页）、\"文本块＋图谱三元组\"保守证据链协议、六类幻觉检测方法对比（MCC 下降 44%～84%）；支撑\"答案＋文本证据＋图谱路径\"证据链设计（必备落点）",
        "lang": "英文",
        "cand_title": "一种基于扩散模型和知识图谱的智能金融问答系统的关键技术研究",
        "cand_authors": "翟源昊（导师：陈佃军，页面未提供导师字段）",
        "cand_source": "硕士学位论文，北京邮电大学，2025（表中未写学校，页面补足）",
        "cand_volpage": "学位论文无卷期页：学位授予单位 北京邮电大学、学位级别 硕士、学位授予年份 2025",
        "cnki_id": "CDMD-10013-1025075409",
        "cand_url": "https://cdmd.cnki.com.cn/Article/CDMD-10013-1025075409.htm",
        "verdict": "核实通过（题录一致）",
        "verdict_note": "题名、作者、学位类型与年份一致；表中未写学位授予单位，页面为\"北京邮电大学\"（属补充信息）；表中\"导师：陈佃军\"页面未提供，无法核实",
        "evidence": D + "FIN-20.html / FIN-20.txt",
        "fulltext": "②需登录下载（页面\"下载全文\"入口无直达 href；未点击）",
        "found": "奠基性（基准类）：HalluBench 的证据链协议与幻觉检测对比数据是本课题\"答案＋文本证据＋图谱路径\"落点的直接对标，无中文等价替代",
        "recommend": "建议谨慎：本候选是\"扩散模型＋KG 的金融问答系统\"，不含幻觉基准与证据链协议，撑不住原落点；采纳需同时保留 HalluBench，并把候选改作\"国内金融 KG 问答系统实现\"的例证",
        "alt": "池内 FIN-24（金融决策支持知识获取综述）更贴\"证据/知识获取\"，但不含幻觉评测",
    },
    {
        "code": "SYS-4",
        "orig": "A Layered Architecture for Developing and Enhancing Capabilities in Large Language Model-based Software Systems（D. Zhang 等，arXiv:2411.12357, 2024）",
        "pos": "《04》3.4（L106）；参考文献[20]",
        "purpose": "面向 LLM 的软件系统分层架构框架（模型层/推理层/应用层）与分层对能力扩展、工程复杂度、运维成本的影响；支撑六层架构与前后端分离的分层职责论证",
        "lang": "英文",
        "cand_title": "水利知识图谱与大模型双向赋能技术探索",
        "cand_authors": "钱峰、沈乃政、刘业森、张保生、陆宇、刘杰、彭天赦",
        "cand_source": "《中国防汛抗旱》2026 年第 09 期",
        "cand_volpage": "卷号与页码页面未提供（仅年到 2026、期到 09）",
        "cnki_id": "CJFDTOTAL-FHKH202609011",
        "cand_url": "https://www.cnki.com.cn/Article/CJFDTotal-FHKH202609011.htm",
        "verdict": "核实通过（题录一致）",
        "verdict_note": "题名与表中一致；作者表中写\"钱峰、沈乃政、刘业森等\"，页面为 7 位作者全列（属补充信息）",
        "evidence": D + "SYS-4.html / SYS-4.txt",
        "fulltext": "②需登录下载（页面\"下载全文\"入口，指向 wap.cnki.net；未点击）",
        "found": "无等价替代：LLM 软件系统分层架构的中文文献稀缺；候选是\"KG↔大模型双向赋能\"技术体系，不含软件分层架构论证",
        "recommend": "不建议采纳（对原论点疑似不相关）：撑不住\"模型层/推理层/应用层分层职责\"；建议原英文架构文献保留，或在池内改选 SYS-2（Langchain-LLMs 智能问答系统设计与实现，延边大学 2024）承担\"系统分层实现\"",
        "alt": "池内 SYS-2《基于Langchain-LLMs框架的智能问答系统的设计与实现》（延边大学硕士学位论文 2024）；SYS-16《基于大语言模型的知识图谱构建及应用研究》（计算机科学与探索 2024, 18(10): 2656-2667）；SYS-18《融合知识图谱和大模型的高校科研管理问答系统设计》（计算机科学与探索 2025, 19(1): 107-117）",
    },
    {
        "code": "SYS-8",
        "orig": "HybridRAG: Integrating Knowledge Graphs and Vector Retrieval Augmented Generation for Efficient Information Extraction（B. Sarmah 等，arXiv:2408.04948, 2024）",
        "pos": "《04》3.2（L74）；3.4（L110）；参考文献[12]",
        "purpose": "双路拼接式路线：向量检索＋图谱检索两路召回、拼接为上下文送入 LLM；在金融（财报电话会议）文本上验证\"向量检索模块＋图谱检索模块\"双路结构可行性",
        "lang": "英文",
        "cand_title": "基于Hybrid RAG的LLM水产营养推荐架构",
        "cand_authors": "高佳、艾新宇、张胜茂",
        "cand_source": "《上海海洋大学学报》2026 年第 04 期",
        "cand_volpage": "卷号与页码页面未提供（仅年到 2026、期到 04）",
        "cnki_id": "CJFDTOTAL-SSDB202604002",
        "cand_url": "https://www.cnki.com.cn/Article/CJFDTotal-SSDB202604002.htm",
        "verdict": "核实通过（题录一致）",
        "verdict_note": "题名、三位作者、刊期与表中一致",
        "evidence": D + "SYS-8.html / SYS-8.txt",
        "fulltext": "②需登录下载（页面\"下载全文\"入口，指向 wap.cnki.net；未点击）",
        "found": "开创性（工程范式）：HybridRAG 在金融文本上的双路实现是本课题双路结构的直接来源，中文候选是同一范式在水产领域的迁移，不能替代\"金融场景可行性\"的原有证据",
        "recommend": "可采纳为\"Hybrid RAG 架构在国内（水产营养）的落地实例\"，但\"金融文本上的双路可行性\"仍须引 Sarmah 2024；正文需按领域改写表述",
        "alt": "池内 SYS-5《基于大模型检索增强生成的计算机网络实验课程问答系统设计与实现》（实验技术与管理 2024, 41(12): 186-192）可作 RAG 系统实现的补充",
    },
    {
        "code": "SYS-13",
        "orig": "RAGPerf: An End-to-End Benchmarking Framework for Retrieval-Augmented Generation Systems（S. Li 等，PVLDB 2026, 19(11): 3689-3703）",
        "pos": "《04》3.4（L116）；参考文献[22]",
        "purpose": "把 RAG 流程拆成 embedding、indexing、retrieval、reranking、generation 五个可配置组件，逐组件改变参数并观测端到端查询性能与答案质量；工作负载生成器与吞吐/主机资源指标；支撑系统指标口径、消融 A～E 的组件级变量控制与实验配置固定表",
        "lang": "英文",
        "cand_title": "融合检索增强生成技术的国产轻量化大语言模型在肺癌专科问题解答中的效能评估",
        "cand_authors": "任治臻、李奕乐、马一卓、陈麒至、李吉利、杨思艺、张健豪、秦科、蒲强、陈楠、刘伦旭",
        "cand_source": "《中国胸心血管外科临床杂志》2026 年第 09 期",
        "cand_volpage": "卷号与页码页面未提供（仅年到 2026、期到 09）",
        "cnki_id": "CJFDTOTAL-ZXYX202609007",
        "cand_url": "https://www.cnki.com.cn/Article/CJFDTotal-ZXYX202609007.htm",
        "verdict": "题录有出入（题名）",
        "verdict_note": "表中所写\"……在专科问题解答中的效能评估\" vs 页面实际\"……在肺癌专科问题解答中的效能评估\"——表中题名漏\"肺癌\"二字；作者表中写\"任治臻等\"，页面为 11 位作者全列；刊期一致",
        "evidence": D + "SYS-13.html / SYS-13.txt",
        "fulltext": "②需登录下载（页面\"下载全文\"入口，指向 wap.cnki.net；未点击）",
        "found": "无等价替代：RAGPerf 的五组件可配置基准与端到端性能/资源指标无中文等价替代；候选是\"11 款国产轻量模型＋有无 RAG 对比\"的效能评估实践",
        "recommend": "建议采纳但必须更正题名（补\"肺癌\"），并改写论证口径为\"国内 RAG 效能评估实践（医学专科域）\"；组件级基准与实验配置固定表的口径仍须引 RAGPerf",
        "alt": "池内无 RAG 基准框架类中文文献；SYS-5 可作 RAG 系统评测的补充",
    },
    {
        "code": "SYS-14",
        "orig": "HetaRAG: Hybrid Deep Retrieval-Augmented Generation across Heterogeneous Data Stores（G. Yan 等，arXiv:2509.21336, 2025）",
        "pos": "《04》3.4（L112）；3.5（L128）；参考文献[21]",
        "purpose": "四类异构检索范式（向量、知识图谱、全文索引、关系引擎）的固有权衡分析与协同检索编排主张；支撑三存储（MySQL、Neo4j、向量索引）与证据追溯链路、多存储协同总体设计",
        "lang": "英文",
        "cand_title": "基于知识图谱路径推理和大模型的电力智能检索引擎",
        "cand_authors": "薛子强、张逸、郑宗华、李传栋、姜海燕",
        "cand_source": "《电网技术》2026 年第 08 期",
        "cand_volpage": "卷号与页码页面未提供（仅年到 2026、期到 08）",
        "cnki_id": "CJFDTOTAL-DWJS202608019",
        "cand_url": "https://www.cnki.com.cn/Article/CJFDTotal-DWJS202608019.htm",
        "verdict": "核实通过（题录一致）",
        "verdict_note": "题名与表中一致；作者表中写\"薛子强、张逸、郑宗华等\"，页面为 5 位作者全列（属补充信息）",
        "evidence": D + "SYS-14.html / SYS-14.txt",
        "fulltext": "②需登录下载（页面\"下载全文\"入口，指向 wap.cnki.net；未点击）",
        "found": "开创性（工程框架）：HetaRAG 对四类异构检索范式的权衡与\"多存储协同编排而非收敛到单一后端\"的主张无中文等价替代；候选是 KG 路径推理＋大模型检索引擎，不涉及多存储编排",
        "recommend": "可采纳为\"KG 路径推理＋大模型检索引擎（电力域）\"的国内实例，但多存储协同设计与证据追溯链路的论据仍须引 HetaRAG；若不改写论证口径，建议不采纳",
        "alt": "池内 SYS-6《面向多源异质数据源的学科知识图谱构建方法》（计算机系统应用 2021, 30(10): 59-67）偏多源异质数据融合，可作\"多源\"补充",
    },
]

# 逐条对照表（表中所写 vs 页面实际），用于核实明细
TABLE_FIELDS = {
    "KG-5": {
        "表中所写": "题名：基于注意力机制的知识图谱推理方法研究；作者：刘晓鹏；导师：赵军；硕士学位论文，宁夏大学，2026",
        "页面实际": "题名一致；作者：刘晓鹏；【学位授予单位】宁夏大学；【学位级别】硕士；【学位授予年份】2026；页面无\"导师\"字段（出现 0 次）",
    },
    "KG-9": {
        "表中所写": "题名：基于多维指令集微调的大语言模型金融事件抽取；作者：杨维、才智杰；《计算机科学与探索》2026 年第 8 期",
        "页面实际": "题名一致；作者：杨维、才智杰；《计算机科学与探索》2026 年 08 期；卷号/页码未提供",
    },
    "KG-16": {
        "表中所写": "题名：基于跨度和网络结构的篇章级事件抽取研究；作者：牛冰宇；导师：廖涛；硕士学位论文，2026（未写学校）",
        "页面实际": "题名一致；作者：牛冰宇；【学位授予单位】安徽理工大学；硕士；2026；页面无\"导师\"字段",
    },
    "KG-17": {
        "表中所写": "题名：基于自适应GNN的篇章级金融事件抽取系统研究与实现；作者：廖慧之；导师：臧洁；硕士学位论文，辽宁大学，2025",
        "页面实际": "题名、作者、辽宁大学、硕士、2025 均一致；页面无\"导师\"字段",
    },
    "KG-19": {
        "表中所写": "题名：外部知识增强的事件共指消解方法；作者：徐昇、李培峰、朱巧明；《软件学报》（未写年/期）",
        "页面实际": "题名一致；作者一致；《软件学报》2025 年 11 期（补充年份与期号）；卷号/页码未提供",
    },
    "KG-29": {
        "表中所写": "题名：面向开源情报的实体链接技术研究综述；作者：韩雪、陈秋琼、戴耀、胡佳荣；《情报工程》2025 年第 3 期",
        "页面实际": "题名一致；作者一致；《情报工程》2025 年 03 期；卷号/页码未提供",
    },
    "RAG-1": {
        "表中所写": "题名：检索增强生成综述：方法与应用；作者：王鑫林、李岩、马超凡、李硕；《计算机科学》2026 年第 7 期",
        "页面实际": "题名一致；作者一致；《计算机科学》2026 年 07 期；卷号/页码未提供",
    },
    "RAG-9": {
        "表中所写": "题名：融合双驱动检索与结构安全增强的GraphRAG多跳推理方法研究；作者：陈岩；导师：顾树俊；硕士学位论文，齐鲁工业大学，2026",
        "页面实际": "题名、作者、齐鲁工业大学、硕士、2026 均一致；页面无\"导师\"字段；摘要栏为空（未公开摘要）",
    },
    "RAG-10": {
        "表中所写": "题名：基于图神经网络推理的知识图谱多跳问答方法研究；作者：王东际；导师：卢玲；硕士学位论文，重庆理工大学，2026",
        "页面实际": "题名、作者、重庆理工大学、硕士、2026 均一致；页面无\"导师\"字段",
    },
    "RAG-11": {
        "表中所写": "题名：基于文本图结构化的层次化检索增强生成方法；作者：雋兆波；《计算机工程与设计》2026 年第 8 期",
        "页面实际": "题名一致；作者：雋兆波；《计算机工程与设计》2026 年 08 期；卷号/页码未提供",
    },
    "RAG-13": {
        "表中所写": "题名：基于检索增强的大语言模型问答方法研究；作者：何伯磊；导师：凌震华；博士学位论文，中国科学技术大学，2026",
        "页面实际": "题名、作者、中国科学技术大学、博士、2026 均一致；页面无\"导师\"字段",
    },
    "RAG-24": {
        "表中所写": "题名：AIGC嵌入图书馆知识发现服务的幻觉识别与信任度测量；作者：禤德信；《情报探索》2026 年第 9 期",
        "页面实际": "题名一致；作者：禤德信；《情报探索》2026 年 09 期；卷号/页码未提供",
    },
    "FIN-3": {
        "表中所写": "题名：基于检索增强生成的金融智能问答方法研究；作者：冯宇；导师：杜方；硕士学位论文，宁夏大学，2026",
        "页面实际": "题名、作者、宁夏大学、硕士、2026 均一致；页面无\"导师\"字段",
    },
    "FIN-16": {
        "表中所写": "题名：基于多粒度隐含时态感知的时序知识图谱问答研究；作者：方纪祥；导师：卢玲；硕士学位论文，重庆理工大学，2026",
        "页面实际": "题名、作者、重庆理工大学、硕士、2026 均一致；页面无\"导师\"字段",
    },
    "FIN-17": {
        "表中所写": "题名：SARIMA嵌入的时序知识图谱推理；作者：吴钰、胡友德、冯桐等；《电子技术应用》2026 年第 6 期",
        "页面实际": "题名一致；作者 7 位全列：吴钰、胡友德、冯桐、杜滢明、曹晗、唐静、李新兵；《电子技术应用》2026 年 06 期；卷号/页码未提供",
    },
    "FIN-20": {
        "表中所写": "题名：一种基于扩散模型和知识图谱的智能金融问答系统的关键技术研究；作者：翟源昊；导师：陈佃军；硕士学位论文，2025（未写学校）",
        "页面实际": "题名一致；作者：翟源昊；【学位授予单位】北京邮电大学；硕士；2025；页面无\"导师\"字段",
    },
    "SYS-4": {
        "表中所写": "题名：水利知识图谱与大模型双向赋能技术探索；作者：钱峰、沈乃政、刘业森等；《中国防汛抗旱》2026 年第 9 期",
        "页面实际": "题名一致；作者 7 位全列；《中国防汛抗旱》2026 年 09 期；卷号/页码未提供",
    },
    "SYS-8": {
        "表中所写": "题名：基于Hybrid RAG的LLM水产营养推荐架构；作者：高佳、艾新宇、张胜茂；《上海海洋大学学报》2026 年第 4 期",
        "页面实际": "题名一致；作者一致；《上海海洋大学学报》2026 年 04 期；卷号/页码未提供",
    },
    "SYS-13": {
        "表中所写": "题名：融合检索增强生成技术的国产轻量化大语言模型在专科问题解答中的效能评估；作者：任治臻等；《中国胸心血管外科临床杂志》2026 年第 9 期",
        "页面实际": "题名实为\"……在肺癌专科问题解答中的效能评估\"（表中漏\"肺癌\"）；作者 11 位全列，第一作者任治臻；刊期一致；卷号/页码未提供",
    },
    "SYS-14": {
        "表中所写": "题名：基于知识图谱路径推理和大模型的电力智能检索引擎；作者：薛子强、张逸、郑宗华等；《电网技术》2026 年第 8 期",
        "页面实际": "题名一致；作者 5 位全列；《电网技术》2026 年 08 期；卷号/页码未提供",
    },
}
